language: node_js
node_js:
  - "20"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc imagemagick

script: make

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  fqdn: spawnedshelter.com
  on:
    branch: master
